services:
  client:
    build:
      context: .
      dockerfile: client.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../entryParsing:/entryParsing
      - ~/.kaggle/distribuidos:/datasets
    