services:
  client:
    build:
      context: ./client
      dockerfile: client.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./entryParsing:/entryParsing
      - ~/.kaggle/distribuidos:/datasets
    