filterer-action:
  build:
    context: ./filterer
    dockerfile: ../rabbitUser.Dockerfile
  environment:
    - PYTHONUNBUFFERED=1
    - FILTERER_TYPE=2
    - LISTENING_QUEUE=FilterAction
    - NEXT_NODE=JoinerActionNegativeReviewsEnglish,2,0;JoinerActionPercentile,2,0
  env_file:
    - .env
  volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
  networks:
    - sa_net
