services:
  rabbitmq:
      build:
        context: ./rabbitmq
        dockerfile: rabbitmq.dockerfile
      ports:
        - 15672:15672
      networks:
        - sa_net
networks:
  sa_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24