services:
  grouper:
    build:
      context: ./grouperPositiveReviews
      dockerfile: grouperPositiveReviews.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./grouperReviews:/grouperReviews
    networks: 
      - sa_net
networks:
  sa_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24