services:
  client:
    build:
      context: ./client
      dockerfile: ../zmqUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./entryParsing:/entryParsing
      - ~/.kaggle/distribuidos:/datasets
      - ./client/responses:/responses
    networks:
      - sa_net
    depends_on:
      - border-node

  border-node:
    build:
      context: ./borderNode
      dockerfile: ../zmqUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
    networks:
      - sa_net
    depends_on:
      - initializer
      - filterer-indie
      - filterer-date
      - sorter-avg-playtime-1
      - sorter-avg-playtime-2
      - sorter-consolidator-avg-playtime
      - grouper-indie
      - joiner-indie-positive-1
      - joiner-indie-positive-2
      - joiner-indie-consolidator
      - sorter-indie-positive-reviews-1
      - sorter-indie-positive-reviews-2
      - sorter-consolidator-indie-top
      - grouper-os-counts
      - joiner-os-counts
      - joiner-action-english-1
      - joiner-action-english-2
      - filterer-english-1
      - filterer-english-2
      - filterer-english-3
      - filterer-english-4
      - filterer-english-5
      - filterer-english-6
      - filterer-english-7
      - filterer-english-8
      - grouper-action-english
      - joiner-english-count-1
      - joiner-english-count-2
      - joiner-english-consolidator
      - joiner-stream-consolidator
      - filterer-action
      - grouper-action-percentile
      - joiner-action-percentile-1
      - joiner-action-percentile-2
      - sorter-consolidator-action-percentile

  initializer:
    build:
      context: ./initializer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
    networks:
      - sa_net
    
  grouper-os-counts:
    build:
      context: ./grouper
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - GROUPER_TYPE=0
      - LISTENING_QUEUE=GrouperOSCounts
      - NEXT_NODES=JoinerOsCounts
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  joiner-os-counts:
    build:
      context: ./joinerCount
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_COUNT_TYPE=0
      - HOST=rabbitmq
      - LISTENING_QUEUE=JoinerOsCounts
      - NEXT_NODES=Dispatcher
      - QUERY_NUMBER=1
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  filterer-indie:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - FILTERER_TYPE=1
      - LISTENING_QUEUE=FilterIndie
      - NEXT_NODES=FilterDecade;JoinerIndiePositiveReviews,2,0
      - HOST=rabbitmq
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  filterer-date:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - FILTERER_TYPE=0
      - LISTENING_QUEUE=FilterDecade
      - NEXT_NODES=SorterAvgPlaytime,2,1
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  sorter-avg-playtime-1:
    build:
      context: ./sorter
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - SORTER_TYPE=0
      - NODE_ID=0
      - NODE_COUNT=2
      - TOP_AMOUNT=10
      - LISTENING_QUEUE=SorterAvgPlaytime
      - NEXT_NODES=ConsolidatorSorterAvgPlaytime
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  sorter-avg-playtime-2:
    build:
      context: ./sorter
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - SORTER_TYPE=0
      - NODE_ID=1
      - NODE_COUNT=2
      - TOP_AMOUNT=10
      - LISTENING_QUEUE=SorterAvgPlaytime
      - NEXT_NODES=ConsolidatorSorterAvgPlaytime
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  sorter-consolidator-avg-playtime:
    build:
      context: ./sorter
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - SORTER_TYPE=2
      - TOP_AMOUNT=10
      - QUERY_NUMBER=2
      - PRIOR_NODE_COUNT=2
      - LISTENING_QUEUE=ConsolidatorSorterAvgPlaytime
      - NEXT_NODES=Dispatcher
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  grouper-indie:
    build:
      context: ./grouper
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - GROUPER_TYPE=1
      - LISTENING_QUEUE=GrouperIndiePositiveReviews
      - NEXT_NODES=JoinerIndiePositiveReviews,2,0
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  joiner-indie-positive-1:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=0
      - JOINER_TYPE=1
      - LISTENING_QUEUE=JoinerIndiePositiveReviews
      - NEXT_NODES=ConsolidatorJoinerIndiePositiveReviews
      - HOST=rabbitmq
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  joiner-indie-positive-2:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=1
      - JOINER_TYPE=1
      - LISTENING_QUEUE=JoinerIndiePositiveReviews
      - NEXT_NODES=ConsolidatorJoinerIndiePositiveReviews
      - HOST=rabbitmq
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  joiner-indie-consolidator:
    build:
      context: ./joinerConsolidator
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_CONSOLIDATOR_TYPE=2
      - LISTENING_QUEUE=ConsolidatorJoinerIndiePositiveReviews
      - NEXT_NODES=SorterIndiePositiveReviews,2,1
      - PRIOR_NODE_COUNT=2
      - HOST=rabbitmq
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  sorter-indie-positive-reviews-1:
    build:
      context: ./sorter
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - SORTER_TYPE=1
      - NODE_ID=0
      - NODE_COUNT=2
      - TOP_AMOUNT=5
      - LISTENING_QUEUE=SorterIndiePositiveReviews
      - NEXT_NODES=ConsolidatorSorterIndiePositiveReviews
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  sorter-indie-positive-reviews-2:
    build:
      context: ./sorter
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - SORTER_TYPE=1
      - NODE_ID=1
      - NODE_COUNT=2
      - TOP_AMOUNT=5
      - LISTENING_QUEUE=SorterIndiePositiveReviews
      - NEXT_NODES=ConsolidatorSorterIndiePositiveReviews
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  sorter-consolidator-indie-top:
    build:
      context: ./sorter
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - SORTER_TYPE=3
      - TOP_AMOUNT=5
      - QUERY_NUMBER=3
      - PRIOR_NODE_COUNT=2
      - LISTENING_QUEUE=ConsolidatorSorterIndiePositiveReviews
      - NEXT_NODES=Dispatcher
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  filterer-action:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - FILTERER_TYPE=2
      - LISTENING_QUEUE=FilterAction
      - NEXT_NODES=JoinerActionNegativeReviewsEnglish,2,0;JoinerActionPercentile,2,0
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  joiner-action-english-1:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=17
      - HOST=rabbitmq
      - JOINER_TYPE=2
      - NODE_ID=0
      - LISTENING_QUEUE=JoinerActionNegativeReviewsEnglish
      - NEXT_NODES=FilterEnglish
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  joiner-action-english-2:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - JOINER_TYPE=2
      - NODE_ID=1
      - LISTENING_QUEUE=JoinerActionNegativeReviewsEnglish
      - NEXT_NODES=FilterEnglish
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  filterer-english-1:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - FILTERER_TYPE=3
      - LISTENING_QUEUE=FilterEnglish
      - NEXT_NODES=GrouperActionEnglish
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  filterer-english-2:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - FILTERER_TYPE=3
      - LISTENING_QUEUE=FilterEnglish
      - NEXT_NODES=GrouperActionEnglish
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  filterer-english-3:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - FILTERER_TYPE=3
      - LISTENING_QUEUE=FilterEnglish
      - NEXT_NODES=GrouperActionEnglish
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  filterer-english-4:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - FILTERER_TYPE=3
      - LISTENING_QUEUE=FilterEnglish
      - NEXT_NODES=GrouperActionEnglish
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  filterer-english-5:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - FILTERER_TYPE=3
      - LISTENING_QUEUE=FilterEnglish
      - NEXT_NODES=GrouperActionEnglish
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  filterer-english-6:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - FILTERER_TYPE=3
      - LISTENING_QUEUE=FilterEnglish
      - NEXT_NODES=GrouperActionEnglish
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  filterer-english-7:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - FILTERER_TYPE=3
      - LISTENING_QUEUE=FilterEnglish
      - NEXT_NODES=GrouperActionEnglish
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  filterer-english-8:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - FILTERER_TYPE=3
      - LISTENING_QUEUE=FilterEnglish
      - NEXT_NODES=GrouperActionEnglish
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  grouper-action-english:
    build:
      context: ./grouper
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - GROUPER_TYPE=2
      - LISTENING_QUEUE=GrouperActionEnglish
      - NEXT_NODES=ConsolidatorJoinerActionEnglish
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  joiner-english-consolidator:
    build:
      context: ./joinerConsolidator
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_CONSOLIDATOR_TYPE=1
      - PRIOR_NODE_COUNT=2
      - LISTENING_QUEUE=ConsolidatorJoinerActionEnglish
      - NEXT_NODES=JoinerNegativeReviewsEnglishCount,2,0
      - HOST=rabbitmq
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  joiner-english-count-1:
    build:
      context: ./joinerCount
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_COUNT_TYPE=1
      - HOST=rabbitmq
      - NODE_ID=0
      - REQUIRED_REVIEWS=5000
      - LISTENING_QUEUE=JoinerNegativeReviewsEnglishCount
      - NEXT_NODES=JoinerStreamConsolidator
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  joiner-english-count-2:
    build:
      context: ./joinerCount
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_COUNT_TYPE=1
      - HOST=rabbitmq
      - NODE_ID=1
      - REQUIRED_REVIEWS=5000
      - LISTENING_QUEUE=JoinerNegativeReviewsEnglishCount
      - NEXT_NODES=JoinerStreamConsolidator
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  joiner-stream-consolidator:
    build:
      context: ./joinerConsolidator
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PRIOR_NODE_COUNT=2
      - JOINER_CONSOLIDATOR_TYPE=0
      - LISTENING_QUEUE=JoinerStreamConsolidator
      - NEXT_NODES=Dispatcher
      - HOST=rabbitmq
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  grouper-action-percentile:
    build:
      context: ./grouper
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - GROUPER_TYPE=1
      - LISTENING_QUEUE=GrouperActionPercentile
      - NEXT_NODES=JoinerActionPercentile,2,0
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  joiner-action-percentile-1:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_TYPE=0
      - HOST=rabbitmq
      - NODE_ID=0
      - LISTENING_QUEUE=JoinerActionPercentile
      - NEXT_NODES=ConsolidatorSorterActionPercentile
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  joiner-action-percentile-2:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - JOINER_TYPE=0
      - NODE_ID=1
      - LISTENING_QUEUE=JoinerActionPercentile
      - NEXT_NODES=ConsolidatorSorterActionPercentile
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

  sorter-consolidator-action-percentile:
    build:
      context: ./sorter
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=rabbitmq
      - SORTER_TYPE=4
      - PERCENTILE=90
      - QUERY_NUMBER=5
      - PRIOR_NODE_COUNT=2
      - LISTENING_QUEUE=ConsolidatorSorterActionPercentile
      - NEXT_NODES=Dispatcher
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sendingStrategy:/sendingStrategy
    networks:
      - sa_net

networks:
  sa_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
