services:  
  client:
    build:
      context: ./client
      dockerfile: ../zmqUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./entryParsing:/entryParsing
      - ~/.kaggle/distribuidos:/datasets
    networks: 
      - sa_net
    depends_on:
      - border-node

  border-node:
    build:
      context: ./borderNode
      dockerfile: ../zmqUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
    networks: 
      - sa_net
    depends_on:
      - initializer
      - filterer-action
      - grouper-action-percentile
      - joiner-action-percentile-1
      - joiner-action-percentile-2
      - sorter-consolidator-action-percentile

  initializer:
    build:
      context: ./initializer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
    networks: 
      - sa_net

  filterer-action:
    build:
      context: ./filtererAction
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./filterer:/filterer
    networks: 
      - sa_net

  grouper-action-percentile:
    build:
      context: ./grouperActionPercentile
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./grouperReviews:/grouperReviews
    networks: 
      - sa_net

  joiner-action-percentile-1:
    build:
      context: ./joinerActionPercentile
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=0
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./joiner:/joiner
    networks: 
      - sa_net

  joiner-action-percentile-2:
    build:
      context: ./joinerActionPercentile
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./joiner:/joiner
    networks: 
      - sa_net

  sorter-consolidator-action-percentile:
    build:
      context: ./sorterConsolidatorActionPercentile
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sorter:/sorter
    networks: 
      - sa_net

networks:
  sa_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24