name: distribuidos-tp
services:
  client:
    build:
      context: ./client
      dockerfile: ../zmqUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    volumes:
    - ./entryParsing:/entryParsing
    - ~/.kaggle/distribuidos:/datasets
    - ./client/responses:/responses
    networks:
    - sa_net
    depends_on:
    - border-node
  initializer:
    build:
      context: ./initializer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  grouper-os-counts:
    build:
      context: ./grouper
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=GrouperOSCounts
    - NEXT_NODES=JoinerOsCounts
    - GROUPER_TYPE=0
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    networks:
    - sa_net
  filterer-indie:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=FilterIndie
    - NEXT_NODES=FilterDecade;JoinerIndiePositiveReviews,2,0
    - FILTERER_TYPE=1
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    networks:
    - sa_net
  filterer-date:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=FilterDecade
    - NEXT_NODES=SorterAvgPlaytime,2,1
    - FILTERER_TYPE=0
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    networks:
    - sa_net
  grouper-iindie:
    build:
      context: ./grouper
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=GrouperIndiePositiveReviews
    - NEXT_NODES=JoinerIndiePositiveReviews,2,0
    - GROUPER_TYPE=1
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    networks:
    - sa_net
  joiner-indie-positive-1:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=JoinerIndiePositiveReviews
    - NEXT_NODES=ConsolidatorJoinerIndiePositiveReviews
    - JOINER_TYPE=1
    - NODE_ID=1
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    - ./packetTracker:/packetTracker
    networks:
    - sa_net
  joiner-indie-positive-2:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=JoinerIndiePositiveReviews
    - NEXT_NODES=ConsolidatorJoinerIndiePositiveReviews
    - JOINER_TYPE=1
    - NODE_ID=2
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    - ./packetTracker:/packetTracker
    networks:
    - sa_net
  joiner-indie-consolidator:
    build:
      context: ./joinerConsolidator
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=ConsolidatorJoinerIndiePositiveReviews
    - NEXT_NODES=SorterIndiePositiveReviews,2,1
    - JOINER_CONSOLIDATOR_TYPE=2
    - PRIOR_NODE_COUNT=2
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    - ./packetTracker:/packetTracker
    networks:
    - sa_net
  filterer-action:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=FilterAction
    - NEXT_NODES=JoinerActionNegativeReviewsEnglish,2,0;JoinerActionPercentile,2,0
    - FILTERER_TYPE=2
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    networks:
    - sa_net
  joiner-action-english-1:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=JoinerActionNegativeReviewsEnglish
    - NEXT_NODES=FilterEnglish
    - JOINER_TYPE=2
    - NODE_ID=1
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    - ./packetTracker:/packetTracker
    networks:
    - sa_net
  joiner-action-english-2:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=JoinerActionNegativeReviewsEnglish
    - NEXT_NODES=FilterEnglish
    - JOINER_TYPE=2
    - NODE_ID=2
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    - ./packetTracker:/packetTracker
    networks:
    - sa_net
  filterer-english-1:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=FilterEnglish
    - NEXT_NODES=GrouperActionEnglish
    - FILTERER_TYPE=3
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    networks:
    - sa_net
  filterer-english-2:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=FilterEnglish
    - NEXT_NODES=GrouperActionEnglish
    - FILTERER_TYPE=3
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    networks:
    - sa_net
  filterer-english-3:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=FilterEnglish
    - NEXT_NODES=GrouperActionEnglish
    - FILTERER_TYPE=3
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    networks:
    - sa_net
  filterer-english-4:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=FilterEnglish
    - NEXT_NODES=GrouperActionEnglish
    - FILTERER_TYPE=3
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    networks:
    - sa_net
  filterer-english-5:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=FilterEnglish
    - NEXT_NODES=GrouperActionEnglish
    - FILTERER_TYPE=3
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    networks:
    - sa_net
  filterer-english-6:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=FilterEnglish
    - NEXT_NODES=GrouperActionEnglish
    - FILTERER_TYPE=3
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    networks:
    - sa_net
  filterer-english-7:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=FilterEnglish
    - NEXT_NODES=GrouperActionEnglish
    - FILTERER_TYPE=3
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    networks:
    - sa_net
  filterer-english-8:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=FilterEnglish
    - NEXT_NODES=GrouperActionEnglish
    - FILTERER_TYPE=3
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    networks:
    - sa_net
  grouper-action-english:
    build:
      context: ./grouper
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=GrouperActionEnglish
    - NEXT_NODES=ConsolidatorJoinerActionEnglish
    - GROUPER_TYPE=2
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    networks:
    - sa_net
  joiner-english-consolidator:
    build:
      context: ./joinerConsolidator
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=ConsolidatorJoinerActionEnglish
    - NEXT_NODES=JoinerNegativeReviewsEnglishCount,2,0
    - JOINER_CONSOLIDATOR_TYPE=1
    - PRIOR_NODE_COUNT=1
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    - ./packetTracker:/packetTracker
    networks:
    - sa_net
  stream-consolidator:
    build:
      context: ./joinerConsolidator
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=JoinerStreamConsolidator
    - NEXT_NODES=Dispatcher
    - JOINER_CONSOLIDATOR_TYPE=0
    - PRIOR_NODE_COUNT=2
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    - ./packetTracker:/packetTracker
    networks:
    - sa_net
  grouper-action-percentile:
    build:
      context: ./grouper
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=GrouperActionPercentile
    - NEXT_NODES=JoinerActionPercentile,2,0
    - GROUPER_TYPE=1
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    networks:
    - sa_net
  joiner-action-percentile-1:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=JoinerActionPercentile
    - NEXT_NODES=ConsolidatorSorterActionPercentile
    - JOINER_TYPE=0
    - NODE_ID=1
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    - ./packetTracker:/packetTracker
    networks:
    - sa_net
  joiner-action-percentile-2:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - HOST=rabbitmq
    - LISTENING_QUEUE=JoinerActionPercentile
    - NEXT_NODES=ConsolidatorSorterActionPercentile
    - JOINER_TYPE=0
    - NODE_ID=2
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./sendingStrategy:/sendingStrategy
    - ./packetTracker:/packetTracker
    networks:
    - sa_net
  border-node:
    build:
      context: ./borderNode
      dockerfile: ../zmqUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
    depends_on:
    - initializer
    - grouper-os-counts
    - filterer-indie
    - filterer-date
    - grouper-iindie
    - joiner-indie-positive-1
    - joiner-indie-positive-2
    - joiner-indie-consolidator
    - filterer-action
    - joiner-action-english-1
    - joiner-action-english-2
    - filterer-english-1
    - filterer-english-2
    - filterer-english-3
    - filterer-english-4
    - filterer-english-5
    - filterer-english-6
    - filterer-english-7
    - filterer-english-8
    - grouper-action-english
    - joiner-english-consolidator
    - grouper-action-percentile
    - joiner-action-percentile-1
    - joiner-action-percentile-2
networks:
  sa_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
