services:
  client-1:
    build:
      context: ./client
      dockerfile: ../zmqUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - MAX_DATA_BYTES=51200
    - REVIEWS_STORAGE_FILEPATH=./datasets/reviews-reducido.csv
    - GAMES_STORAGE_FILEPATH=./datasets/games-reducido.csv
    - AMOUNT_OF_EXECUTIONS=1
    volumes:
    - ./entryParsing:/entryParsing
    - ~/.kaggle/distribuidos:/datasets
    - ./client-1/responses:/responses
    networks:
    - sa_net
    depends_on:
    - border-node
  initializer-0:
    build:
      context: ./initializer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=Initializer
    - HEADER_TYPE=HeaderWithTable
    - GAMES_ENTRY_TYPE=ReducedGameEntry
    - GAMES_NEXT_NODES=GrouperOSCounts;FilterIndie;FilterAction
    - GAMES_NEXT_ENTRIES=EntryOSSupport;EntryAppIDNameGenresReleaseDateAvgPlaytime;EntryAppIDNameGenres
    - GAMES_NEXT_HEADERS=Header;;
    - REVIEWS_ENTRY_TYPE=ReviewEntry
    - REVIEWS_NEXT_NODES=GrouperIndie;JoinerActionEnglish,2,0;GrouperActionPercentile
    - REVIEWS_NEXT_ENTRIES=EntryAppID;EntryAppIDReviewText;EntryAppID
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  initializer-1:
    build:
      context: ./initializer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=Initializer
    - HEADER_TYPE=HeaderWithTable
    - GAMES_ENTRY_TYPE=ReducedGameEntry
    - GAMES_NEXT_NODES=GrouperOSCounts;FilterIndie;FilterAction
    - GAMES_NEXT_ENTRIES=EntryOSSupport;EntryAppIDNameGenresReleaseDateAvgPlaytime;EntryAppIDNameGenres
    - GAMES_NEXT_HEADERS=Header;;
    - REVIEWS_ENTRY_TYPE=ReviewEntry
    - REVIEWS_NEXT_NODES=GrouperIndie;JoinerActionEnglish,2,0;GrouperActionPercentile
    - REVIEWS_NEXT_ENTRIES=EntryAppID;EntryAppIDReviewText;EntryAppID
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  initializer-2:
    build:
      context: ./initializer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=Initializer
    - HEADER_TYPE=HeaderWithTable
    - GAMES_ENTRY_TYPE=ReducedGameEntry
    - GAMES_NEXT_NODES=GrouperOSCounts;FilterIndie;FilterAction
    - GAMES_NEXT_ENTRIES=EntryOSSupport;EntryAppIDNameGenresReleaseDateAvgPlaytime;EntryAppIDNameGenres
    - GAMES_NEXT_HEADERS=Header;;
    - REVIEWS_ENTRY_TYPE=ReviewEntry
    - REVIEWS_NEXT_NODES=GrouperIndie;JoinerActionEnglish,2,0;GrouperActionPercentile
    - REVIEWS_NEXT_ENTRIES=EntryAppID;EntryAppIDReviewText;EntryAppID
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  grouper-os-counts:
    build:
      context: ./grouper
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=GrouperOSCounts
    - GROUPER_TYPE=0
    - NEXT_NODES=AggregatorOs
    - HEADER_TYPE=Header
    - ENTRY_TYPE=EntryOSSupport
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  aggregator-os:
    build:
      context: ./aggregator
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=AggregatorOs
    - NEXT_NODES=Dispatcher
    - HEADER_TYPE=Header
    - ENTRY_TYPE=EntryOSCount
    - AGGREGATOR_TYPE=0
    - QUERY_NUMBER=1
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./aggregator/AggregatorOs:/AggregatorOs
    networks:
    - sa_net
  filterer-indie:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=FilterIndie
    - FILTERER_TYPE=1
    - NEXT_NODES=FilterDecade;JoinerIndie,2,0
    - NEXT_ENTRIES=EntryNameDateAvgPlaytime;EntryAppIDName
    - NEXT_HEADERS=Header;
    - HEADER_TYPE=HeaderWithTable
    - ENTRY_TYPE=EntryAppIDNameGenresReleaseDateAvgPlaytime
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  filterer-date:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=FilterDecade
    - FILTERER_TYPE=0
    - NEXT_NODES=SorterAvgPlaytime,2,1
    - NEXT_ENTRIES=EntryNameAvgPlaytime
    - HEADER_TYPE=Header
    - ENTRY_TYPE=EntryNameDateAvgPlaytime
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  sorter-playtime-0:
    build:
      context: ./sorter
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=SorterAvgPlaytime
    - NEXT_NODES=ConsolidatorSorterPlaytime
    - HEADER_TYPE=Header
    - ENTRY_TYPE=EntryNameAvgPlaytime
    - NODE_ID=0
    - SORTER_TYPE={0}
    - TOP_AMOUNT={'10'}
    - NODE_COUNT={'2'}
    - NEXT_HEADERS=HeaderWithSender
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./sorter/SorterAvgPlaytime0:/SorterAvgPlaytime
    networks:
    - sa_net
  sorter-playtime-1:
    build:
      context: ./sorter
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=SorterAvgPlaytime
    - NEXT_NODES=ConsolidatorSorterPlaytime
    - HEADER_TYPE=Header
    - ENTRY_TYPE=EntryNameAvgPlaytime
    - NODE_ID=1
    - SORTER_TYPE={0}
    - TOP_AMOUNT={'10'}
    - NODE_COUNT={'2'}
    - NEXT_HEADERS=HeaderWithSender
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./sorter/SorterAvgPlaytime1:/SorterAvgPlaytime
    networks:
    - sa_net
  sorter-consolidator-playtime:
    build:
      context: ./sorter
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=ConsolidatorSorterPlaytime
    - NEXT_NODES=Dispatcher
    - NEXT_HEADERS=HeaderWithQueryNumber
    - HEADER_TYPE=HeaderWithSender
    - ENTRY_TYPE=EntryNameAvgPlaytime
    - SORTER_TYPE={2}
    - PRIOR_NODE_COUNT={'2'}
    - TOP_AMOUNT={'10'}
    - QUERY_NUMBER=2
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./sorter-consolidator/ConsolidatorSorterPlaytime:/ConsolidatorSorterPlaytime
    networks:
    - sa_net
  grouper-indie:
    build:
      context: ./grouper
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=GrouperIndie
    - GROUPER_TYPE=1
    - NEXT_NODES=JoinerIndie,2,0
    - HEADER_TYPE=HeaderWithTable
    - ENTRY_TYPE=EntryAppID
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  joiner-indie-0:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=JoinerIndie
    - JOINER_TYPE=1
    - NEXT_NODES=AggregatorIndie
    - REVIEWS_ENTRY_TYPE=EntryAppIDReviewCount
    - GAMES_ENTRY_TYPE=EntryAppIDName
    - NODE_ID=0
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./joiner/JoinerIndie0:/JoinerIndie
    networks:
    - sa_net
  joiner-indie-1:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=JoinerIndie
    - JOINER_TYPE=1
    - NEXT_NODES=AggregatorIndie
    - REVIEWS_ENTRY_TYPE=EntryAppIDReviewCount
    - GAMES_ENTRY_TYPE=EntryAppIDName
    - NODE_ID=1
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./joiner/JoinerIndie1:/JoinerIndie
    networks:
    - sa_net
  aggregator-indie:
    build:
      context: ./aggregator
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=AggregatorIndie
    - NEXT_NODES=SorterIndie,2,1
    - HEADER_TYPE=HeaderWithSender
    - ENTRY_TYPE=EntryNameReviewCount
    - AGGREGATOR_TYPE=2
    - PRIOR_NODE_COUNT=2
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./aggregator/AggregatorIndie:/AggregatorIndie
    networks:
    - sa_net
  sorter-indie-0:
    build:
      context: ./sorter
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=SorterIndie
    - NEXT_NODES=ConsolidatorSorterIndie
    - NODE_ID=0
    - HEADER_TYPE=Header
    - ENTRY_TYPE=EntryNameReviewCount
    - SORTER_TYPE={1}
    - TOP_AMOUNT={'5'}
    - NODE_COUNT={'2'}
    - NEXT_HEADERS=HeaderWithSender
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./sorter/SorterIndie0:/SorterIndie
    networks:
    - sa_net
  sorter-indie-1:
    build:
      context: ./sorter
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=SorterIndie
    - NEXT_NODES=ConsolidatorSorterIndie
    - NODE_ID=1
    - HEADER_TYPE=Header
    - ENTRY_TYPE=EntryNameReviewCount
    - SORTER_TYPE={1}
    - TOP_AMOUNT={'5'}
    - NODE_COUNT={'2'}
    - NEXT_HEADERS=HeaderWithSender
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./sorter/SorterIndie1:/SorterIndie
    networks:
    - sa_net
  sorter-consolidator-indie:
    build:
      context: ./sorter
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=ConsolidatorSorterIndie
    - NEXT_NODES=Dispatcher
    - NEXT_HEADERS=HeaderWithQueryNumber
    - HEADER_TYPE=HeaderWithSender
    - ENTRY_TYPE=EntryNameReviewCount
    - SORTER_TYPE={3}
    - PRIOR_NODE_COUNT={'2'}
    - TOP_AMOUNT={'5'}
    - QUERY_NUMBER=3
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./sorter-consolidator/ConsolidatorSorterIndie:/ConsolidatorSorterIndie
    networks:
    - sa_net
  filterer-action:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=FilterAction
    - FILTERER_TYPE=2
    - NEXT_NODES=JoinerActionEnglish,2,0;JoinerActionPercentile,2,0
    - NEXT_ENTRIES=EntryAppIDName;EntryAppIDName
    - HEADER_TYPE=HeaderWithTable
    - ENTRY_TYPE=EntryAppIDNameGenres
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  joiner-english-0:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=JoinerActionEnglish
    - JOINER_TYPE=2
    - NEXT_NODES=FilterEnglish
    - REVIEWS_ENTRY_TYPE=EntryAppIDReviewText
    - GAMES_ENTRY_TYPE=EntryAppIDName
    - NODE_ID=0
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./joiner/JoinerActionEnglish0:/JoinerActionEnglish
    networks:
    - sa_net
  joiner-english-1:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=JoinerActionEnglish
    - JOINER_TYPE=2
    - NEXT_NODES=FilterEnglish
    - REVIEWS_ENTRY_TYPE=EntryAppIDReviewText
    - GAMES_ENTRY_TYPE=EntryAppIDName
    - NODE_ID=1
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./joiner/JoinerActionEnglish1:/JoinerActionEnglish
    networks:
    - sa_net
  filterer-english:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=FilterEnglish
    - FILTERER_TYPE=3
    - NEXT_NODES=GrouperActionEnglish
    - NEXT_ENTRIES=EntryAppIDName
    - HEADER_TYPE=HeaderWithSender
    - ENTRY_TYPE=EntryAppIDNameReviewText
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  grouper-english:
    build:
      context: ./grouper
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=GrouperActionEnglish
    - GROUPER_TYPE=2
    - NEXT_NODES=AggregatorEnglish
    - HEADER_TYPE=HeaderWithSender
    - ENTRY_TYPE=EntryAppIDName
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  aggregator-english:
    build:
      context: ./aggregator
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=AggregatorEnglish
    - NEXT_NODES=Dispatcher
    - HEADER_TYPE=HeaderWithSender
    - ENTRY_TYPE=EntryAppIDNameReviewCount
    - AGGREGATOR_TYPE=1
    - QUERY_NUMBER=4
    - PRIOR_NODE_COUNT=2
    - REQUIRED_REVIEWS=5000
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./aggregator/AggregatorEnglish:/AggregatorEnglish
    networks:
    - sa_net
  grouper-percentile:
    build:
      context: ./grouper
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=GrouperActionPercentile
    - GROUPER_TYPE=1
    - NEXT_NODES=JoinerActionPercentile,2,0
    - HEADER_TYPE=HeaderWithTable
    - ENTRY_TYPE=EntryAppID
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  joiner-percentile-0:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=JoinerActionPercentile
    - JOINER_TYPE=0
    - NEXT_NODES=ConsolidatorSorterPercentile
    - REVIEWS_ENTRY_TYPE=EntryAppIDReviewCount
    - GAMES_ENTRY_TYPE=EntryAppIDName
    - NODE_ID=0
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./joiner/JoinerActionPercentile0:/JoinerActionPercentile
    networks:
    - sa_net
  joiner-percentile-1:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=JoinerActionPercentile
    - JOINER_TYPE=0
    - NEXT_NODES=ConsolidatorSorterPercentile
    - REVIEWS_ENTRY_TYPE=EntryAppIDReviewCount
    - GAMES_ENTRY_TYPE=EntryAppIDName
    - NODE_ID=1
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./joiner/JoinerActionPercentile1:/JoinerActionPercentile
    networks:
    - sa_net
  sorter-consolidator-percentile:
    build:
      context: ./sorter
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - LISTENING_QUEUE=ConsolidatorSorterPercentile
    - NEXT_NODES=Dispatcher
    - HEADER_TYPE=HeaderWithSender
    - ENTRY_TYPE=EntryAppIDNameReviewCount
    - SORTER_TYPE={4}
    - PRIOR_NODE_COUNT={'2'}
    - PERCENTILE={'90'}
    - QUERY_NUMBER=5
    - NEXT_HEADERS=HeaderWithQueryNumber
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./sorter-consolidator/ConsolidatorSorterPercentile:/ConsolidatorSorterPercentile
    networks:
    - sa_net
  border-node:
    build:
      context: ./borderNode
      dockerfile: ../zmqUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
    depends_on:
    - initializer-0
    - initializer-1
    - initializer-2
    - grouper-os-counts
    - grouper-os-counts
    - aggregator-os
    - filterer-indie
    - filterer-date
    - sorter-playtime-0
    - sorter-playtime-1
    - sorter-consolidator-playtime
    - grouper-indie
    - joiner-indie-0
    - joiner-indie-1
    - aggregator-indie
    - sorter-indie-0
    - sorter-indie-1
    - sorter-consolidator-indie
    - filterer-action
    - joiner-english-0
    - joiner-english-1
    - filterer-english
    - filterer-english
    - filterer-english
    - filterer-english
    - filterer-english
    - filterer-english
    - filterer-english
    - filterer-english
    - grouper-english
    - aggregator-english
    - grouper-percentile
    - joiner-percentile-0
    - joiner-percentile-1
    - sorter-consolidator-percentile
networks:
  sa_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
