services:
  client-1:
    build:
      context: ./client
      dockerfile: ../zmqUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - MAX_DATA_BYTES=51200
    - REVIEWS_STORAGE_FILEPATH=./datasets/reviews-reducido.csv
    - GAMES_STORAGE_FILEPATH=./datasets/games-reducido.csv
    - AMOUNT_OF_EXECUTIONS=1
    volumes:
    - ./entryParsing:/entryParsing
    - ~/.kaggle/distribuidos:/datasets
    - ./client-1/responses:/responses
    networks:
    - sa_net
    depends_on:
    - border-node
  client-2:
    build:
      context: ./client
      dockerfile: ../zmqUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - MAX_DATA_BYTES=51200
    - REVIEWS_STORAGE_FILEPATH=./datasets/reviews-reducido.csv
    - GAMES_STORAGE_FILEPATH=./datasets/games-reducido.csv
    - AMOUNT_OF_EXECUTIONS=1
    volumes:
    - ./entryParsing:/entryParsing
    - ~/.kaggle/distribuidos:/datasets
    - ./client-2/responses:/responses
    networks:
    - sa_net
    depends_on:
    - border-node
  initializer-0:
    build:
      context: ./initializer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - PREFETCH_COUNT=1
    - LISTENING_QUEUE=Initializer
    - HEADER_TYPE=HeaderWithTable
    - GAMES_ENTRY_TYPE=ReducedGameEntry
    - GAMES_NEXT_NODES=GrouperOSCounts;FilterIndie;FilterAction
    - GAMES_NEXT_ENTRIES=EntryOSSupport;EntryAppIDNameGenresReleaseDateAvgPlaytime;EntryAppIDNameGenres
    - GAMES_NEXT_HEADERS=Header;;
    - REVIEWS_ENTRY_TYPE=ReviewEntry
    - REVIEWS_NEXT_NODES=GrouperIndie;JoinerActionEnglish,3,0;GrouperActionPercentile
    - REVIEWS_NEXT_ENTRIES=EntryAppID;EntryAppIDReviewText;EntryAppID
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  initializer-1:
    build:
      context: ./initializer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - PREFETCH_COUNT=1
    - LISTENING_QUEUE=Initializer
    - HEADER_TYPE=HeaderWithTable
    - GAMES_ENTRY_TYPE=ReducedGameEntry
    - GAMES_NEXT_NODES=GrouperOSCounts;FilterIndie;FilterAction
    - GAMES_NEXT_ENTRIES=EntryOSSupport;EntryAppIDNameGenresReleaseDateAvgPlaytime;EntryAppIDNameGenres
    - GAMES_NEXT_HEADERS=Header;;
    - REVIEWS_ENTRY_TYPE=ReviewEntry
    - REVIEWS_NEXT_NODES=GrouperIndie;JoinerActionEnglish,3,0;GrouperActionPercentile
    - REVIEWS_NEXT_ENTRIES=EntryAppID;EntryAppIDReviewText;EntryAppID
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  initializer-2:
    build:
      context: ./initializer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - PREFETCH_COUNT=1
    - LISTENING_QUEUE=Initializer
    - HEADER_TYPE=HeaderWithTable
    - GAMES_ENTRY_TYPE=ReducedGameEntry
    - GAMES_NEXT_NODES=GrouperOSCounts;FilterIndie;FilterAction
    - GAMES_NEXT_ENTRIES=EntryOSSupport;EntryAppIDNameGenresReleaseDateAvgPlaytime;EntryAppIDNameGenres
    - GAMES_NEXT_HEADERS=Header;;
    - REVIEWS_ENTRY_TYPE=ReviewEntry
    - REVIEWS_NEXT_NODES=GrouperIndie;JoinerActionEnglish,3,0;GrouperActionPercentile
    - REVIEWS_NEXT_ENTRIES=EntryAppID;EntryAppIDReviewText;EntryAppID
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  filterer-action:
    build:
      context: ./filterer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - PREFETCH_COUNT=1
    - LISTENING_QUEUE=FilterAction
    - FILTERER_TYPE=2
    - NEXT_NODES=JoinerActionEnglish,3,0;JoinerActionPercentile,3,0
    - NEXT_ENTRIES=EntryAppIDName;EntryAppIDName
    - HEADER_TYPE=HeaderWithTable
    - ENTRY_TYPE=EntryAppIDNameGenres
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  grouper-percentile:
    build:
      context: ./grouper
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - PREFETCH_COUNT=1
    - LISTENING_QUEUE=GrouperActionPercentile
    - GROUPER_TYPE=1
    - NEXT_NODES=JoinerActionPercentile,3,0
    - HEADER_TYPE=HeaderWithTable
    - ENTRY_TYPE=EntryAppID
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    networks:
    - sa_net
  joiner-percentile-0:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - PREFETCH_COUNT=50
    - LISTENING_QUEUE=JoinerActionPercentile
    - JOINER_TYPE=0
    - NEXT_NODES=ConsolidatorSorterPercentile
    - NEXT_HEADERS=HeaderWithSender
    - REVIEWS_ENTRY_TYPE=EntryAppIDReviewCount
    - GAMES_ENTRY_TYPE=EntryAppIDName
    - HEADER_TYPE=HeaderWithTable
    - NODE_ID=0
    - NODE_COUNT=3
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./statefulNode:/statefulNode
    - ./eofController:/eofController
    - ./joiner/JoinerActionPercentile0:/JoinerActionPercentile
    networks:
    - sa_net
  joiner-percentile-1:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - PREFETCH_COUNT=50
    - LISTENING_QUEUE=JoinerActionPercentile
    - JOINER_TYPE=0
    - NEXT_NODES=ConsolidatorSorterPercentile
    - NEXT_HEADERS=HeaderWithSender
    - REVIEWS_ENTRY_TYPE=EntryAppIDReviewCount
    - GAMES_ENTRY_TYPE=EntryAppIDName
    - HEADER_TYPE=HeaderWithTable
    - NODE_ID=1
    - NODE_COUNT=3
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./statefulNode:/statefulNode
    - ./eofController:/eofController
    - ./joiner/JoinerActionPercentile1:/JoinerActionPercentile
    networks:
    - sa_net
  joiner-percentile-2:
    build:
      context: ./joiner
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - PREFETCH_COUNT=50
    - LISTENING_QUEUE=JoinerActionPercentile
    - JOINER_TYPE=0
    - NEXT_NODES=ConsolidatorSorterPercentile
    - NEXT_HEADERS=HeaderWithSender
    - REVIEWS_ENTRY_TYPE=EntryAppIDReviewCount
    - GAMES_ENTRY_TYPE=EntryAppIDName
    - HEADER_TYPE=HeaderWithTable
    - NODE_ID=2
    - NODE_COUNT=3
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./statefulNode:/statefulNode
    - ./eofController:/eofController
    - ./joiner/JoinerActionPercentile2:/JoinerActionPercentile
    networks:
    - sa_net
  sorter-consolidator-percentile:
    build:
      context: ./sorter
      dockerfile: ../rabbitUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - PREFETCH_COUNT=1
    - LISTENING_QUEUE=ConsolidatorSorterPercentile
    - NEXT_NODES=Dispatcher
    - HEADER_TYPE=HeaderWithSender
    - ENTRY_TYPE=EntryAppIDNameReviewCount
    - SORTER_TYPE=4
    - PRIOR_NODE_COUNT=3
    - PERCENTILE=90
    - QUERY_NUMBER=5
    - NEXT_HEADERS=HeaderWithQueryNumber
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./packetTracker:/packetTracker
    - ./statefulNode:/statefulNode
    - ./eofController:/eofController
    - ./sorter/ConsolidatorSorterPercentile:/ConsolidatorSorterPercentile
    networks:
    - sa_net
  border-node:
    build:
      context: ./borderNode
      dockerfile: ../zmqUser.Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - PREFETCH_COUNT=1
    - STORAGE_PATH=/data/
    - LISTENING_QUEUE=Dispatcher
    env_file:
    - .env
    volumes:
    - ./internalCommunication:/internalCommunication
    - ./entryParsing:/entryParsing
    - ./borderNode/data:/data
    networks:
    - sa_net
    depends_on:
    - initializer-0
    - initializer-1
    - initializer-2
    - filterer-action
    - grouper-percentile
    - joiner-percentile-0
    - joiner-percentile-1
    - joiner-percentile-2
    - sorter-consolidator-percentile
networks:
  sa_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
