services:
  grouper:
    build:
      context: ./grouperPositiveReviews
      dockerfile: grouperPositiveReviews.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./grouperReviews:/grouperReviews
    networks: 
      - sa_net
  mock-joiner1:
    build:
      context: ./mockJoiner
      dockerfile: mockJoiner.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=0
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
    networks: 
      - sa_net
  mock-joiner2:
    build:
      context: ./mockJoiner
      dockerfile: mockJoiner.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
    networks: 
      - sa_net
  producer:
    build:
      context: ./mockProducer
      dockerfile: producer.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
    networks: 
      - sa_net

networks:
  sa_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24