services:  
  client:
    build:
      context: ./client
      dockerfile: ../zmqUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./entryParsing:/entryParsing
      - ~/.kaggle/distribuidos:/datasets
    networks: 
      - sa_net

  border-node:
    build:
      context: ./borderNode
      dockerfile: ../zmqUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
    networks: 
      - sa_net

  initializer:
    build:
      context: ./initializer
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
    networks: 
      - sa_net

  filterer-indie:
    build:
      context: ./filtererIndie
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./filterer:/filterer
    networks: 
      - sa_net

  filterer-date:
    build:
      context: ./filtererDate
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./filterer:/filterer
    networks: 
      - sa_net

  sorter-avg-playtime-1:
    build:
      context: ./sorterAvgPlaytime
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=0
      - TOP_AMOUNT=10
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sorter:/sorter
    networks: 
      - sa_net

  sorter-avg-playtime-2:
    build:
      context: ./sorterAvgPlaytime
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=1
      - TOP_AMOUNT=10
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sorter:/sorter
    networks: 
      - sa_net

  sorter-consolidator-avg-playtime:
    build:
      context: ./sorterConsolidatorAvgPlaytime
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - TOP_AMOUNT=10
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sorter:/sorter
    networks: 
      - sa_net

  grouper-indie:
    build:
      context: ./grouperIndiePositiveReviews
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./grouperReviews:/grouperReviews
    networks: 
      - sa_net

  joiner-indie-positive-1:
    build:
      context: ./joinerIndiePositive
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=0
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./joiner:/joiner
    networks: 
      - sa_net

  joiner-indie-positive-2:
    build:
      context: ./joinerIndiePositive
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./joiner:/joiner
    networks: 
      - sa_net

  joiner-indie-consolidator:
    build:
      context: ./joinerIndieConsolidator
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./joiner:/joiner
    networks:
      - sa_net
    
  sorter-indie-positive-reviews-1:
    build:
      context: ./sorterIndiePositiveReviews
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=0
      - TOP_AMOUNT=5
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sorter:/sorter
    networks: 
      - sa_net

  sorter-indie-positive-reviews-2:
    build:
      context: ./sorterIndiePositiveReviews
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=1
      - TOP_AMOUNT=5
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sorter:/sorter
    networks: 
      - sa_net

  sorter-consolidator-indie-top:
    build:
      context: ./sorterConsolidatorIndieTop
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - TOP_AMOUNT=5
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
      - ./sorter:/sorter
    networks: 
      - sa_net

  grouper-os-counts:
    build:
      context: ./grouperOSCounts
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
    networks: 
      - sa_net

  joiner-os-counts:
    build:
      context: ./joinerOSCount
      dockerfile: ../rabbitUser.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./internalCommunication:/internalCommunication
      - ./entryParsing:/entryParsing
      - ./packetTracker:/packetTracker
    networks: 
      - sa_net

networks:
  sa_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24